### GENERAL
languageCode: en-us
author:
    name: Serhii Vasylenko
    email: email-from-blog@vasylenko.info
    
theme: "PaperMod"
paginate: 5
### BUILD
publishDir: publishdir
minify:
    disableXML: true
    minifyOutput: true

### SEO
enableRobotsTXT: true
title: Serhii Vasylenko — Technical Blog

### NAVIGATION
permalinks:
  posts: :year/:month/:day/:slug

menu:
    main:
        - identifier: about
          name: "About me"
          url: /about/
          weight: 21
        - identifier: archive
          name: "All posts"
          url: /archive
          weight: 20
        - identifier: category
          name: "RSS Feed"
          url: /index.xml
          weight: 1
        - identifier: cv
          name: "My CV"
          url: /cv/
          weight: 30

### DECORATIONS
markup:
    highlight:
        # anchorLineNos: true
        codeFences: true
        guessSyntax: false
        lineNos: false
        noClasses: true
        style: native

# TAXONOMY
taxonomies:
    series: series

outputs:
    home:
        - HTML
        - JSON # is necessary
        - RSS

rssLimit: 20

# disqusShortname:

### THEME SETTINGS
params:
    SubscribeEngagement: false
    ShowLicense: true
    WriteMeOnTwitter: true
    title: Serhii Vasylenko — Technical Blog
    description: "Developer Experience Engineer at Grammarly and AWS Community Builder. The blog is about AWS, Terraform, and different DevOps stuff."
    keywords: [Technical Blog, DevOps, AWS, Terraform, Ukraine, Tutorials, Education, DeveloperExperience]
    author: Serhii Vasylenko
    images: ["/assets/img/website-logo.png"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false
    ShowFullTextinRSS: true
    ShowReadingTime: false
    ShowShareButtons: false
    ShareButtons: ["twitter", "linkedin", "facebook", "reddit"]
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    schema:
        publisherType: "Person"

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "/favicon.ico"
        favicon16x16: "/favicon-16x16.png"
        favicon32x32: "/favicon-32x32.png"
        apple_touch_icon: "/apple-touch-icon.png"
        safari_pinned_tab: "/safari-pinned-tab.svg"

    label:
        text: "Home"
        icon: "/apple-touch-icon.png"

    homeInfoParams:
        Title: "Welcome to my technical blog!"
        Content: "Here I write about my DevOps experience, technologies, and some day-to-day work as a Developer Experience engineer at Grammarly. But not only 🙃. I sincerely hope you’ll enjoy reading me!"

#     socialIcons:
#         - name: twitter
#           url: "https://twitter.com/vasylenko"
#         - name: dev
#           url: "https://dev.to/svasylenko"
#         - name: linkedin
#           url: "https://www.linkedin.com/in/svasylenko/"
#         - name: github
#           url: "https://github.com/vasylenko"
#         - name: "facebook"
#           url: "https://www.facebook.com/vasylenkos"

    cover:
        hidden: false # hide everywhere but not in structured data
        hiddenInList: false # hide on list pages and home
        hiddenInSingle: false # hide on single page
        responsiveImages: true

    editPost:
        URL: "mailto:email-from-blog@vasylenko.info"
        Text: "📩 Suggest Changes"
        appendFilePath: false

    # for search
    # https://fusejs.io/api/options.html
#     fuseOpts:
#         isCaseSensitive: false
#         shouldSort: true
#         location: 0
#         distance: 1000
#         threshold: 0.4
#         minMatchCharLength: 0
#         keys: ["title", "permalink", "summary", "content"]