### GENERAL
languageCode: en-us

theme: "PaperMod"

### BUILD
publishDir: publishdir
minify:
    disableXML: true
    minifyOutput: true

### SEO
enableRobotsTXT: true
title: Serhii Vasylenko

### NAVIGATION
permalinks:
  posts: :year/:month/:day/:slug

menu:
    main:
        - identifier: about
          name: "About me"
          url: /about/
          weight: 22
        - identifier: category
          name: "Categories"
          url: /categories/
          weight: 1
        - identifier: search
          name: "Search"
          url: /search/
          weight: 11
        - identifier: cv
          name: "My CV"
          url: /cv/
          weight: 33

### DECORATIONS
markup:
    highlight:
        # anchorLineNos: true
        codeFences: true
        guessSyntax: false
        lineNos: false
        noClasses: true
        style: native

# TAXONOMY
taxonomies:
    category: categories
    tag: tags

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

rssLimit: 20

# disqusShortname:

### THEME SETTINGS
params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Serhii Vasylenko — Personal Blog
    description: "Personal blog of Serhii Vasylenko — AWS Community Builder, Developer Experience Engineer at Grammarly"
    keywords: [Technical Blog, DevOps, AWS, Terraform, Ukraine, Tutorials, Education]
    author: Serhii Vasylenko
    images: ["/assets/img/website-logo-open-graph.jpeg"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false
    ShowFullTextinRSS: true
    ShowReadingTime: false
    ShowShareButtons: true
    ShareButtons: ["twitter", "linkedin", "facebook", "reddit"]
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: false

    schema:
        publisherType: "Person"

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "/favicon.ico"
        favicon16x16: "/favicon-16x16.png"
        favicon32x32: "/favicon-32x32.png"
        apple_touch_icon: "/apple-touch-icon.png"
        safari_pinned_tab: "/safari-pinned-tab.svg"

    label:
        text: "Home"
        icon: "/apple-touch-icon.png"

    homeInfoParams:
        Title: "Hi! 👋 I am Serhii Vasylenko and this is my blog"
        Content: "Here I write about my DevOps experience, technologies, tutorials and some day-to-day work as a Developer Experience engineer at Grammarly. I sincerely hope you’ll enjoy reading me!"
#     socialIcons:
#         - name: twitter
#           url: "https://twitter.com/vasylenko"
#         - name: dev
#           url: "https://dev.to/svasylenko"
#         - name: linkedin
#           url: "https://www.linkedin.com/in/svasylenko/"
#         - name: github
#           url: "https://github.com/vasylenko"
#         - name: "facebook"
#           url: "https://www.facebook.com/vasylenkos"

    cover:
        hidden: false # hide everywhere but not in structured data
        hiddenInList: false # hide on list pages and home
        hiddenInSingle: false # hide on single page
        responsiveImages: true

    editPost:
        URL: "mailto:email-from-blog@vasylenko.info"
        Text: "📩 Suggest Changes"
        appendFilePath: false

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]