name: 'Build Hugo'
description: 'This action build my hugo blod for preview or production env'
inputs:
  env:  # id of input
    description: 'Environment name: preview or production'
    required: true
    default: 'preview'
  build-artifact:
    description: 'Build artifact'
    required: true
    default: 'deployment-artifact'
runs:
  using: "composite"
  steps:
    - name: Prepare Hugo Docker Image
      shell: bash
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
        if [[ docker manifest inspect $(docker compose config --images) ]]; then
          echo "✅ Docker image ghcr.io/vasylenko/hugo-runtime:${{ inputs.hugo-version }} already exists"
          echo "⏭️ Skipping to website build..."
        else
          docker compose build --push
        fi
    - name: Build Preview website
      shell: bash
      if: ${{ inputs.env == 'preview' }}
      run: docker compose run hugo-runtime --environment development --destination ${{ inputs.build-artifact }} --baseURL="" --templateMetrics --templateMetricsHints
    - name: Build Production website
      shell: bash
      if: ${{ inputs.env == 'production' }}
      run: docker compose run hugo-runtime --environment production --destination ${{ inputs.build-artifact }} --gc --minify