name: Website
on:
  push:
    paths:
      - '**'
      - '!.vscode/**'
      - '!cv/**'
      - '!operations/**'
      - '!.github/**'
      - '.github/workflows/website.yaml'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vasylenko/jekyllblogbuilder:latest
      env:
        LANG: "en_US.UTF-8"
        LANGUAGE: "en_US:en"
        LC_ALL: "en_US.UTF-8"
    steps:
      - name: Checkout
        uses: actions/checkout@v2 

      - name: Build blog
        run: |
          bundle install
          bundle exec jekyll build --verbose --destination _site
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: _site
          path: _site

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    env:
      BRANCH: gh-pages-new-theme
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: '${{ env.BRANCH }}'

      - name: Get the build artifact
        uses: actions/download-artifact@v2
        with:
          name: _site
          path: ./

      - name: Deploy (push) to gh-pages
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "${GITHUB_ACTOR}@bots.github.com"
          git add -A 
          git commit -a -m "Updated Website"
          git remote set-url origin "https://x-access-token:${{ secrets.DEPLOY_TOKEN }}@github.com/vasylenko/serhii.vasylenko.info.git"
          git push --force-with-lease origin ${{ env.BRANCH }}

  purge_cf_cache:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Purge CloudFlare cache for website
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLAREZONEID }}/purge_cache" \
               -H "Authorization: Bearer ${{ secrets.CLOUDFLAREPURGETOKEN }}" \
               -H "Content-Type: application/json" \
               --data '{"purge_everything":true}'